# Database
spring:
  application:
    name: carteirada
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carteirada_db
    username: root
    password: guerra4321
    initialization-mode: always
  api:
    versao: 1.0.0
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    format_sql: true